{
  "hash": "2ef79fc8b32aaaaa31348b07a114bf56",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Calibración con Metas Cuasicensales (PEB 2025)\"\nformat: \n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: show\n    theme: cosmo\n---\n\n## 1. Contexto y Objetivos Generales\n\nEn este documento desarrollo el proceso de **calibración con fuentes cuasicensales** para las muestras de **3.er año** y **6.º año de Educación Primaria (PEB 2025)**.\n\nEl objetivo es lograr un vector de ponderadores calibrados ($w_{\\text{cal}}$) único por estudiante que:\n\n1.  Respete el diseño polietápico original ($w_{\\text{diseño}}$).\n2.  Corrija los sesgos derivados de la no respuesta observada en campo ($w_{\\text{NR}}$).\n3.  **Reproduzca exactamente las metas de la publicación cuasicensal**, consistentes en una tabla cruzada $3 \\times 2$ entre **Sector** (Estatal / Privado) y **Nivel Socioeconómico (NSE)** (Bajo, Medio, Alto), garantizando la coincidencia de:\n    - La matrícula poblacional estimada por celda ($N_h$).\n    - La media poblacional de la prueba de **Matemática** ($\\bar{Y}_{\\text{mat}, h}$).\n    - La media poblacional de la prueba de **Lengua / Prácticas del Lenguaje** ($\\bar{Y}_{\\text{pl}, h}$).\n\n\n::: {.cell}\n\n:::\n\n\n------------------------------------------------------------------------\n\n# TERCER AÑO\n\n## 2. Metas Poblacionales Cuasicensales (3.er Año)\n\nDefino la tabla de referencia que sintetiza las medias publicadas obtenidas a partir de las bases cuasicensales evaluadas de 3.er año:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels_NSE = c(\"Bajo\", \"Medio\", \"Alto\")\n\n# Medias publicadas por el operativo cuasicensal (Sector x NSE) para 3.°\nmedias_cuasicenso_3 = tribble(\n  ~sector,   ~NSE,    ~media_mat_ref, ~media_pl_ref,\n  \"Estatal\", \"Bajo\",  66.4,           68.10,\n  \"Estatal\", \"Medio\", 67.0,           72.08,\n  \"Estatal\", \"Alto\",  69.7,           75.54,\n  \"Privado\", \"Bajo\",  68.8,           72.41,\n  \"Privado\", \"Medio\", 72.0,           76.52,\n  \"Privado\", \"Alto\",  72.5,           75.93\n) |>\n  mutate(NSE = factor(NSE, levels = levels_NSE))\n\nmedias_cuasicenso_3 |>\n  gt() |>\n  tab_header(\n    title = \"Metas Poblacionales de la Publicación Cuasicensal\",\n    subtitle = \"Medias de IRA en Matemática y Prácticas del Lenguaje (3.° Año)\"\n  ) |>\n  cols_label(\n    sector = \"Sector\",\n    NSE = \"NSE (Tercil AUH)\",\n    media_mat_ref = \"Media Matemática\",\n    media_pl_ref = \"Media Lengua (PL)\"\n  ) |>\n  fmt_number(columns = c(media_mat_ref, media_pl_ref), decimals = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gdzeafopjn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gdzeafopjn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gdzeafopjn thead, #gdzeafopjn tbody, #gdzeafopjn tfoot, #gdzeafopjn tr, #gdzeafopjn td, #gdzeafopjn th {\n  border-style: none;\n}\n\n#gdzeafopjn p {\n  margin: 0;\n  padding: 0;\n}\n\n#gdzeafopjn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gdzeafopjn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gdzeafopjn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gdzeafopjn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gdzeafopjn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gdzeafopjn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gdzeafopjn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gdzeafopjn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gdzeafopjn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gdzeafopjn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gdzeafopjn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gdzeafopjn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gdzeafopjn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gdzeafopjn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gdzeafopjn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gdzeafopjn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gdzeafopjn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gdzeafopjn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gdzeafopjn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gdzeafopjn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gdzeafopjn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gdzeafopjn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gdzeafopjn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gdzeafopjn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gdzeafopjn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gdzeafopjn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gdzeafopjn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gdzeafopjn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gdzeafopjn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gdzeafopjn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gdzeafopjn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gdzeafopjn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gdzeafopjn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gdzeafopjn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gdzeafopjn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gdzeafopjn .gt_left {\n  text-align: left;\n}\n\n#gdzeafopjn .gt_center {\n  text-align: center;\n}\n\n#gdzeafopjn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gdzeafopjn .gt_font_normal {\n  font-weight: normal;\n}\n\n#gdzeafopjn .gt_font_bold {\n  font-weight: bold;\n}\n\n#gdzeafopjn .gt_font_italic {\n  font-style: italic;\n}\n\n#gdzeafopjn .gt_super {\n  font-size: 65%;\n}\n\n#gdzeafopjn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gdzeafopjn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gdzeafopjn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gdzeafopjn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gdzeafopjn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gdzeafopjn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gdzeafopjn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gdzeafopjn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gdzeafopjn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style>Metas Poblacionales de la Publicación Cuasicensal</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Medias de IRA en Matemática y Prácticas del Lenguaje (3.° Año)</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sector\">Sector</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"NSE\">NSE (Tercil AUH)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"media_mat_ref\">Media Matemática</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"media_pl_ref\">Media Lengua (PL)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Estatal</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Bajo</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">66.40</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">68.10</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Estatal</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Medio</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">67.00</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">72.08</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Estatal</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Alto</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">69.70</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">75.54</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Privado</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Bajo</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">68.80</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">72.41</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Privado</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Medio</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">72.00</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">76.52</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Privado</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Alto</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">72.50</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">75.93</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## 3. Carga del Marco Muestral y Diseño Base (3.er Año)\n\nCargo el marco muestral y calculo la matrícula estimada de 3.er año:\n\n\n::: {.cell}\n\n:::\n\n\n------------------------------------------------------------------------\n\n## 4. Construcción de Ponderadores de Diseño y No Respuesta (3.er Año)\n\n\n::: {.cell}\n\n:::\n\n\n------------------------------------------------------------------------\n\n## 5. Calibración y Diagnóstico (3.er Año)\n\n\n::: {.cell}\n\n:::\n\n\n### Contraste Muestra vs. Metas (3.er Año)\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mirhxnblbl\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mirhxnblbl table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mirhxnblbl thead, #mirhxnblbl tbody, #mirhxnblbl tfoot, #mirhxnblbl tr, #mirhxnblbl td, #mirhxnblbl th {\n  border-style: none;\n}\n\n#mirhxnblbl p {\n  margin: 0;\n  padding: 0;\n}\n\n#mirhxnblbl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mirhxnblbl .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mirhxnblbl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mirhxnblbl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mirhxnblbl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mirhxnblbl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mirhxnblbl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mirhxnblbl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mirhxnblbl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mirhxnblbl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mirhxnblbl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mirhxnblbl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mirhxnblbl .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mirhxnblbl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mirhxnblbl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mirhxnblbl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mirhxnblbl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mirhxnblbl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mirhxnblbl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mirhxnblbl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mirhxnblbl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mirhxnblbl .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mirhxnblbl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mirhxnblbl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mirhxnblbl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mirhxnblbl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mirhxnblbl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mirhxnblbl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mirhxnblbl .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mirhxnblbl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mirhxnblbl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mirhxnblbl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mirhxnblbl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mirhxnblbl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mirhxnblbl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mirhxnblbl .gt_left {\n  text-align: left;\n}\n\n#mirhxnblbl .gt_center {\n  text-align: center;\n}\n\n#mirhxnblbl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mirhxnblbl .gt_font_normal {\n  font-weight: normal;\n}\n\n#mirhxnblbl .gt_font_bold {\n  font-weight: bold;\n}\n\n#mirhxnblbl .gt_font_italic {\n  font-style: italic;\n}\n\n#mirhxnblbl .gt_super {\n  font-size: 65%;\n}\n\n#mirhxnblbl .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mirhxnblbl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mirhxnblbl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mirhxnblbl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mirhxnblbl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mirhxnblbl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mirhxnblbl .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mirhxnblbl .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mirhxnblbl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"10\" class=\"gt_heading gt_title gt_font_normal\" style>Contraste de Medias y Totales: Muestra Calibrada vs. Cuasicenso</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"10\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Tercer Año (PEB 2025)</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sector\">Sector</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"NSE\">NSE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"media_mat_cal\">Mat Calibrada</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"media_mat_ref\">Mat Meta</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dif_mat\">Dif Mat</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"media_pl_cal\">PL Calibrada</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"media_pl_ref\">PL Meta</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dif_pl\">Dif PL</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"N_calibrado\">N Calibrado</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"N_celda\">N Meta</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Estatal</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Bajo</td>\n<td headers=\"media_mat_cal\" class=\"gt_row gt_right\">66.39</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">66.40</td>\n<td headers=\"dif_mat\" class=\"gt_row gt_right\">−0.01</td>\n<td headers=\"media_pl_cal\" class=\"gt_row gt_right\">67.72</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">68.10</td>\n<td headers=\"dif_pl\" class=\"gt_row gt_right\">−0.38</td>\n<td headers=\"N_calibrado\" class=\"gt_row gt_right\">113,531</td>\n<td headers=\"N_celda\" class=\"gt_row gt_right\">113,531</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Estatal</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Medio</td>\n<td headers=\"media_mat_cal\" class=\"gt_row gt_right\">66.91</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">67.00</td>\n<td headers=\"dif_mat\" class=\"gt_row gt_right\">−0.09</td>\n<td headers=\"media_pl_cal\" class=\"gt_row gt_right\">72.06</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">72.08</td>\n<td headers=\"dif_pl\" class=\"gt_row gt_right\">−0.02</td>\n<td headers=\"N_calibrado\" class=\"gt_row gt_right\">59,825</td>\n<td headers=\"N_celda\" class=\"gt_row gt_right\">59,825</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Estatal</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Alto</td>\n<td headers=\"media_mat_cal\" class=\"gt_row gt_right\">69.35</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">69.70</td>\n<td headers=\"dif_mat\" class=\"gt_row gt_right\">−0.35</td>\n<td headers=\"media_pl_cal\" class=\"gt_row gt_right\">75.05</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">75.54</td>\n<td headers=\"dif_pl\" class=\"gt_row gt_right\">−0.49</td>\n<td headers=\"N_calibrado\" class=\"gt_row gt_right\">7,991</td>\n<td headers=\"N_celda\" class=\"gt_row gt_right\">7,991</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Privado</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Bajo</td>\n<td headers=\"media_mat_cal\" class=\"gt_row gt_right\">68.78</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">68.80</td>\n<td headers=\"dif_mat\" class=\"gt_row gt_right\">−0.02</td>\n<td headers=\"media_pl_cal\" class=\"gt_row gt_right\">71.92</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">72.41</td>\n<td headers=\"dif_pl\" class=\"gt_row gt_right\">−0.49</td>\n<td headers=\"N_calibrado\" class=\"gt_row gt_right\">962</td>\n<td headers=\"N_celda\" class=\"gt_row gt_right\">962</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Privado</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Medio</td>\n<td headers=\"media_mat_cal\" class=\"gt_row gt_right\">71.88</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">72.00</td>\n<td headers=\"dif_mat\" class=\"gt_row gt_right\">−0.12</td>\n<td headers=\"media_pl_cal\" class=\"gt_row gt_right\">76.26</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">76.52</td>\n<td headers=\"dif_pl\" class=\"gt_row gt_right\">−0.26</td>\n<td headers=\"N_calibrado\" class=\"gt_row gt_right\">27,643</td>\n<td headers=\"N_celda\" class=\"gt_row gt_right\">27,643</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Privado</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Alto</td>\n<td headers=\"media_mat_cal\" class=\"gt_row gt_right\">72.47</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">72.50</td>\n<td headers=\"dif_mat\" class=\"gt_row gt_right\">−0.03</td>\n<td headers=\"media_pl_cal\" class=\"gt_row gt_right\">75.83</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">75.93</td>\n<td headers=\"dif_pl\" class=\"gt_row gt_right\">−0.10</td>\n<td headers=\"N_calibrado\" class=\"gt_row gt_right\">69,506</td>\n<td headers=\"N_celda\" class=\"gt_row gt_right\">69,506</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### B. Comparación Global: Muestra Calibrada vs. Parámetros Poblacionales (Marco Muestral)\n\nEn esta tabla comparo las distribuciones marginales (porcentajes de estudiantes y notas medias) obtenidas con la muestra calibrada respecto a la población objetivo total del marco muestral de establecimientos:\n\n\n::: {#tbl-comparacion_calib_poblacion_global_3 .cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zzeaeiwygz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zzeaeiwygz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zzeaeiwygz thead, #zzeaeiwygz tbody, #zzeaeiwygz tfoot, #zzeaeiwygz tr, #zzeaeiwygz td, #zzeaeiwygz th {\n  border-style: none;\n}\n\n#zzeaeiwygz p {\n  margin: 0;\n  padding: 0;\n}\n\n#zzeaeiwygz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zzeaeiwygz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zzeaeiwygz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zzeaeiwygz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zzeaeiwygz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zzeaeiwygz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zzeaeiwygz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zzeaeiwygz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zzeaeiwygz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zzeaeiwygz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zzeaeiwygz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zzeaeiwygz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zzeaeiwygz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zzeaeiwygz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zzeaeiwygz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zzeaeiwygz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zzeaeiwygz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zzeaeiwygz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zzeaeiwygz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zzeaeiwygz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zzeaeiwygz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zzeaeiwygz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zzeaeiwygz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zzeaeiwygz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zzeaeiwygz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zzeaeiwygz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zzeaeiwygz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zzeaeiwygz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zzeaeiwygz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zzeaeiwygz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zzeaeiwygz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zzeaeiwygz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zzeaeiwygz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zzeaeiwygz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zzeaeiwygz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zzeaeiwygz .gt_left {\n  text-align: left;\n}\n\n#zzeaeiwygz .gt_center {\n  text-align: center;\n}\n\n#zzeaeiwygz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zzeaeiwygz .gt_font_normal {\n  font-weight: normal;\n}\n\n#zzeaeiwygz .gt_font_bold {\n  font-weight: bold;\n}\n\n#zzeaeiwygz .gt_font_italic {\n  font-style: italic;\n}\n\n#zzeaeiwygz .gt_super {\n  font-size: 65%;\n}\n\n#zzeaeiwygz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zzeaeiwygz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zzeaeiwygz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zzeaeiwygz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zzeaeiwygz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zzeaeiwygz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zzeaeiwygz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zzeaeiwygz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zzeaeiwygz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDYXJhY3RlcsOtc3RpY2EqKg==\"><span class='gt_from_md'><strong>Característica</strong></span></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"level 1; stat_0_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNdWVzdHJhIENhbGlicmFkYSAoMy7CsCBBw7FvKSoq\"><span class='gt_from_md'><strong>Muestra Calibrada (3.° Año)</strong></span></span></div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"level 1; stat_0_2\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipQb2JsYWNpw7NuIE9iamV0aXZvIChNYXJjbykqKg==\"><span class='gt_from_md'><strong>Población Objetivo (Marco)</strong></span></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0_1\"><span data-qmd-base64=\"KipOID0gMjc5LjQ1OCoq\"><span class='gt_from_md'><strong>N = 279.458</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0_2\"><span data-qmd-base64=\"KipOID0gMjc5LjQ1OCoq\"><span class='gt_from_md'><strong>N = 279.458</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sector</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Estatal</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">64,9% (n=2.938)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">64,9%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Privado</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">35,1% (n=2.292)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">35,1%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Nivel Socioeconómico (NSE)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Bajo</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">41,0% (n=1.530)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">41,0%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Medio</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">31,3% (n=1.762)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">31,3%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Alto</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">27,7% (n=1.938)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">27,7%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Zona (Conurbano vs. Interior)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Conurbano</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">80,3% (n=3.663)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">78,9%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Interior</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">19,7% (n=1.567)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">21,1%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Región Educativa</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    01</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">5,5% (n=215)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">5,9%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    02</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">6,1% (n=390)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">8,5%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    03</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">8,1% (n=424)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">9,4%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    04</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">7,3% (n=324)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">9,0%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    05</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">15,2% (n=313)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">8,7%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    06</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">6,2% (n=328)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">6,0%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    07</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">6,6% (n=335)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">4,3%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    08</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">2,2% (n=233)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">6,2%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    09</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">11,7% (n=482)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">10,7%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    10</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">3,6% (n=224)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">3,6%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    11</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">7,7% (n=395)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">6,6%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    12</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,8% (n=200)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">2,0%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    13</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">2,0% (n=85)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,3%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    14</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0,9% (n=90)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,4%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    15</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,7% (n=111)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,3%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    16</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0,3% (n=60)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">0,8%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    17</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0,5% (n=40)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">0,7%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    18</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">2,2% (n=125)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,7%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    19</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">3,1% (n=296)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">3,9%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    20</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,0% (n=128)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,7%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    21</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0,2% (n=49)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">0,8%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    22</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,6% (n=195)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">2,4%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    23</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0,5% (n=51)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">0,8%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    24</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,4% (n=63)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">0,9%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    25</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">2,6% (n=74)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,3%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Ámbito</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Rural Agrupado</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0,5% (n=143)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,4%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Rural Disperso</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,4% (n=175)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,3%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Urbano</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">98,2% (n=4.912)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">97,4%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Jornada Completa</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NO</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">89,1% (n=4.496)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">89,1%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    SI</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">10,9% (n=734)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">10,9%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">% Alumnos con AUH</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">36,25 (0,18)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">0,36</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Media IRA Matemática</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">68,71 (0,02)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Desconocido</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">20.334</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Media IRA Lengua (PL)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">71,82 (0,02)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Desconocido</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">20.413</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Media IRA Matemática (Poblacional)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">68,70</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Media IRA Lengua (Poblacional)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">71,96</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"JSAobj1uICh1bndlaWdodGVkKSk7IE1lZGlhIChTRSk=\"><span class='gt_from_md'>% (n=n (unweighted)); Media (SE)</span></span></td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> <span data-qmd-base64=\"JTsgTWVkaWE=\"><span class='gt_from_md'>%; Media</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# SEXTO AÑO\n\n## 6. Metas Poblacionales Cuasicensales (6.º Año)\n\nExtraigo las metas cuasicensales directamente a partir de las bases de 6.º año evaluadas (`PEB_2025_Primaria_MAT_A6.sav` y `PEB_2025_Primaria_PL_A6.sav`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Medias del cuasicenso para 6.° año\nmedias_cuasicenso_6 = tribble(\n  ~sector,   ~NSE,    ~media_mat_ref, ~media_pl_ref,\n  \"Estatal\", \"Bajo\",  66.58,          71.86,\n  \"Estatal\", \"Medio\", 65.11,          71.43,\n  \"Estatal\", \"Alto\",  63.63,          70.72,\n  \"Privado\", \"Bajo\",  63.02,          74.79,\n  \"Privado\", \"Medio\", 70.30,          78.43,\n  \"Privado\", \"Alto\",  68.64,          76.24\n) |>\n  mutate(NSE = factor(NSE, levels = levels_NSE))\n\nmedias_cuasicenso_6 |>\n  gt() |>\n  tab_header(\n    title = \"Metas Poblacionales del Cuasicenso (6.° Año)\",\n    subtitle = \"Medias de IRA en Matemática y Prácticas del Lenguaje\"\n  ) |>\n  cols_label(\n    sector = \"Sector\",\n    NSE = \"NSE (Tercil AUH)\",\n    media_mat_ref = \"Media Matemática\",\n    media_pl_ref = \"Media Lengua (PL)\"\n  ) |>\n  fmt_number(columns = c(media_mat_ref, media_pl_ref), decimals = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vqamqhrfcc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vqamqhrfcc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vqamqhrfcc thead, #vqamqhrfcc tbody, #vqamqhrfcc tfoot, #vqamqhrfcc tr, #vqamqhrfcc td, #vqamqhrfcc th {\n  border-style: none;\n}\n\n#vqamqhrfcc p {\n  margin: 0;\n  padding: 0;\n}\n\n#vqamqhrfcc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vqamqhrfcc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vqamqhrfcc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vqamqhrfcc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vqamqhrfcc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vqamqhrfcc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vqamqhrfcc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vqamqhrfcc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vqamqhrfcc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vqamqhrfcc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vqamqhrfcc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vqamqhrfcc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vqamqhrfcc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vqamqhrfcc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vqamqhrfcc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vqamqhrfcc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vqamqhrfcc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vqamqhrfcc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vqamqhrfcc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqamqhrfcc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vqamqhrfcc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vqamqhrfcc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vqamqhrfcc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqamqhrfcc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vqamqhrfcc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vqamqhrfcc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vqamqhrfcc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqamqhrfcc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vqamqhrfcc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vqamqhrfcc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vqamqhrfcc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vqamqhrfcc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vqamqhrfcc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqamqhrfcc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vqamqhrfcc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vqamqhrfcc .gt_left {\n  text-align: left;\n}\n\n#vqamqhrfcc .gt_center {\n  text-align: center;\n}\n\n#vqamqhrfcc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vqamqhrfcc .gt_font_normal {\n  font-weight: normal;\n}\n\n#vqamqhrfcc .gt_font_bold {\n  font-weight: bold;\n}\n\n#vqamqhrfcc .gt_font_italic {\n  font-style: italic;\n}\n\n#vqamqhrfcc .gt_super {\n  font-size: 65%;\n}\n\n#vqamqhrfcc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vqamqhrfcc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vqamqhrfcc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vqamqhrfcc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vqamqhrfcc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vqamqhrfcc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vqamqhrfcc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vqamqhrfcc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vqamqhrfcc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style>Metas Poblacionales del Cuasicenso (6.° Año)</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Medias de IRA en Matemática y Prácticas del Lenguaje</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sector\">Sector</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"NSE\">NSE (Tercil AUH)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"media_mat_ref\">Media Matemática</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"media_pl_ref\">Media Lengua (PL)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Estatal</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Bajo</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">66.58</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">71.86</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Estatal</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Medio</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">65.11</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">71.43</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Estatal</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Alto</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">63.63</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">70.72</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Privado</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Bajo</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">63.02</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">74.79</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Privado</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Medio</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">70.30</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">78.43</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Privado</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Alto</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">68.64</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">76.24</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## 7. Carga del Marco Muestral y Diseño Base (6.º Año)\n\n\n::: {.cell}\n\n:::\n\n\n------------------------------------------------------------------------\n\n## 8. Construcción de Ponderadores de Diseño y No Respuesta (6.º Año)\n\n\n::: {.cell}\n\n:::\n\n\n------------------------------------------------------------------------\n\n## 9. Calibración y Diagnóstico (6.º Año)\n\n\n::: {.cell}\n\n:::\n\n\n### Contraste Muestra vs. Metas (6.º Año)\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"cxaqrzlerl\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#cxaqrzlerl table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#cxaqrzlerl thead, #cxaqrzlerl tbody, #cxaqrzlerl tfoot, #cxaqrzlerl tr, #cxaqrzlerl td, #cxaqrzlerl th {\n  border-style: none;\n}\n\n#cxaqrzlerl p {\n  margin: 0;\n  padding: 0;\n}\n\n#cxaqrzlerl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#cxaqrzlerl .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#cxaqrzlerl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#cxaqrzlerl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#cxaqrzlerl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cxaqrzlerl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cxaqrzlerl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cxaqrzlerl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#cxaqrzlerl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#cxaqrzlerl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#cxaqrzlerl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#cxaqrzlerl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#cxaqrzlerl .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#cxaqrzlerl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#cxaqrzlerl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#cxaqrzlerl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#cxaqrzlerl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#cxaqrzlerl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#cxaqrzlerl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cxaqrzlerl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#cxaqrzlerl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#cxaqrzlerl .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#cxaqrzlerl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cxaqrzlerl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#cxaqrzlerl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#cxaqrzlerl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cxaqrzlerl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cxaqrzlerl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#cxaqrzlerl .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cxaqrzlerl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#cxaqrzlerl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cxaqrzlerl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cxaqrzlerl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cxaqrzlerl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cxaqrzlerl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cxaqrzlerl .gt_left {\n  text-align: left;\n}\n\n#cxaqrzlerl .gt_center {\n  text-align: center;\n}\n\n#cxaqrzlerl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#cxaqrzlerl .gt_font_normal {\n  font-weight: normal;\n}\n\n#cxaqrzlerl .gt_font_bold {\n  font-weight: bold;\n}\n\n#cxaqrzlerl .gt_font_italic {\n  font-style: italic;\n}\n\n#cxaqrzlerl .gt_super {\n  font-size: 65%;\n}\n\n#cxaqrzlerl .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#cxaqrzlerl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#cxaqrzlerl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#cxaqrzlerl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#cxaqrzlerl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#cxaqrzlerl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#cxaqrzlerl .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#cxaqrzlerl .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#cxaqrzlerl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"10\" class=\"gt_heading gt_title gt_font_normal\" style>Contraste de Medias y Totales: Muestra Calibrada vs. Cuasicenso</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"10\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Sexto Año (PEB 2025)</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sector\">Sector</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"NSE\">NSE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"media_mat_cal\">Mat Calibrada</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"media_mat_ref\">Mat Meta</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dif_mat\">Dif Mat</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"media_pl_cal\">PL Calibrada</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"media_pl_ref\">PL Meta</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dif_pl\">Dif PL</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"N_calibrado\">N Calibrado</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"N_celda\">N Meta</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Estatal</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Bajo</td>\n<td headers=\"media_mat_cal\" class=\"gt_row gt_right\">66.57</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">66.58</td>\n<td headers=\"dif_mat\" class=\"gt_row gt_right\">−0.01</td>\n<td headers=\"media_pl_cal\" class=\"gt_row gt_right\">72.10</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">71.86</td>\n<td headers=\"dif_pl\" class=\"gt_row gt_right\">0.24</td>\n<td headers=\"N_calibrado\" class=\"gt_row gt_right\">118,130</td>\n<td headers=\"N_celda\" class=\"gt_row gt_right\">118,130</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Estatal</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Medio</td>\n<td headers=\"media_mat_cal\" class=\"gt_row gt_right\">65.11</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">65.11</td>\n<td headers=\"dif_mat\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"media_pl_cal\" class=\"gt_row gt_right\">71.49</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">71.43</td>\n<td headers=\"dif_pl\" class=\"gt_row gt_right\">0.06</td>\n<td headers=\"N_calibrado\" class=\"gt_row gt_right\">62,248</td>\n<td headers=\"N_celda\" class=\"gt_row gt_right\">62,248</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Estatal</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Alto</td>\n<td headers=\"media_mat_cal\" class=\"gt_row gt_right\">63.63</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">63.63</td>\n<td headers=\"dif_mat\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"media_pl_cal\" class=\"gt_row gt_right\">69.22</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">70.72</td>\n<td headers=\"dif_pl\" class=\"gt_row gt_right\">−1.50</td>\n<td headers=\"N_calibrado\" class=\"gt_row gt_right\">8,314</td>\n<td headers=\"N_celda\" class=\"gt_row gt_right\">8,314</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Privado</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Bajo</td>\n<td headers=\"media_mat_cal\" class=\"gt_row gt_right\">63.07</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">63.02</td>\n<td headers=\"dif_mat\" class=\"gt_row gt_right\">0.05</td>\n<td headers=\"media_pl_cal\" class=\"gt_row gt_right\">75.58</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">74.79</td>\n<td headers=\"dif_pl\" class=\"gt_row gt_right\">0.79</td>\n<td headers=\"N_calibrado\" class=\"gt_row gt_right\">1,001</td>\n<td headers=\"N_celda\" class=\"gt_row gt_right\">1,001</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Privado</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Medio</td>\n<td headers=\"media_mat_cal\" class=\"gt_row gt_right\">70.24</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">70.30</td>\n<td headers=\"dif_mat\" class=\"gt_row gt_right\">−0.06</td>\n<td headers=\"media_pl_cal\" class=\"gt_row gt_right\">78.39</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">78.43</td>\n<td headers=\"dif_pl\" class=\"gt_row gt_right\">−0.04</td>\n<td headers=\"N_calibrado\" class=\"gt_row gt_right\">28,763</td>\n<td headers=\"N_celda\" class=\"gt_row gt_right\">28,763</td></tr>\n    <tr><td headers=\"sector\" class=\"gt_row gt_left\">Privado</td>\n<td headers=\"NSE\" class=\"gt_row gt_center\">Alto</td>\n<td headers=\"media_mat_cal\" class=\"gt_row gt_right\">68.64</td>\n<td headers=\"media_mat_ref\" class=\"gt_row gt_right\">68.64</td>\n<td headers=\"dif_mat\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"media_pl_cal\" class=\"gt_row gt_right\">76.25</td>\n<td headers=\"media_pl_ref\" class=\"gt_row gt_right\">76.24</td>\n<td headers=\"dif_pl\" class=\"gt_row gt_right\">0.01</td>\n<td headers=\"N_calibrado\" class=\"gt_row gt_right\">72,321</td>\n<td headers=\"N_celda\" class=\"gt_row gt_right\">72,321</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### B. Comparación Global: Muestra Calibrada vs. Parámetros Poblacionales (Marco Muestral 6.º Año)\n\n\n::: {#tbl-comparacion_calib_poblacion_global_6 .cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"owaytpvfim\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#owaytpvfim table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#owaytpvfim thead, #owaytpvfim tbody, #owaytpvfim tfoot, #owaytpvfim tr, #owaytpvfim td, #owaytpvfim th {\n  border-style: none;\n}\n\n#owaytpvfim p {\n  margin: 0;\n  padding: 0;\n}\n\n#owaytpvfim .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#owaytpvfim .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#owaytpvfim .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#owaytpvfim .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#owaytpvfim .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#owaytpvfim .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#owaytpvfim .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#owaytpvfim .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#owaytpvfim .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#owaytpvfim .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#owaytpvfim .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#owaytpvfim .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#owaytpvfim .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#owaytpvfim .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#owaytpvfim .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#owaytpvfim .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#owaytpvfim .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#owaytpvfim .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#owaytpvfim .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#owaytpvfim .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#owaytpvfim .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#owaytpvfim .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#owaytpvfim .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#owaytpvfim .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#owaytpvfim .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#owaytpvfim .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#owaytpvfim .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#owaytpvfim .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#owaytpvfim .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#owaytpvfim .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#owaytpvfim .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#owaytpvfim .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#owaytpvfim .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#owaytpvfim .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#owaytpvfim .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#owaytpvfim .gt_left {\n  text-align: left;\n}\n\n#owaytpvfim .gt_center {\n  text-align: center;\n}\n\n#owaytpvfim .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#owaytpvfim .gt_font_normal {\n  font-weight: normal;\n}\n\n#owaytpvfim .gt_font_bold {\n  font-weight: bold;\n}\n\n#owaytpvfim .gt_font_italic {\n  font-style: italic;\n}\n\n#owaytpvfim .gt_super {\n  font-size: 65%;\n}\n\n#owaytpvfim .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#owaytpvfim .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#owaytpvfim .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#owaytpvfim .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#owaytpvfim .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#owaytpvfim .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#owaytpvfim .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#owaytpvfim .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#owaytpvfim div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDYXJhY3RlcsOtc3RpY2EqKg==\"><span class='gt_from_md'><strong>Característica</strong></span></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"level 1; stat_0_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNdWVzdHJhIENhbGlicmFkYSAoNi7CuiBBw7FvKSoq\"><span class='gt_from_md'><strong>Muestra Calibrada (6.º Año)</strong></span></span></div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"level 1; stat_0_2\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipQb2JsYWNpw7NuIE9iamV0aXZvIChNYXJjbykqKg==\"><span class='gt_from_md'><strong>Población Objetivo (Marco)</strong></span></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0_1\"><span data-qmd-base64=\"KipOID0gMjkwLjc3Nyoq\"><span class='gt_from_md'><strong>N = 290.777</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0_2\"><span data-qmd-base64=\"KipOID0gMjkwLjc3Nyoq\"><span class='gt_from_md'><strong>N = 290.777</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Sector</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Estatal</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">64,9% (n=2.842)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">64,9%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Privado</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">35,1% (n=2.184)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">35,1%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Nivel Socioeconómico (NSE)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Bajo</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">41,0% (n=1.473)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">41,0%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Medio</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">31,3% (n=1.692)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">31,3%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Alto</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">27,7% (n=1.861)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">27,7%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Zona (Conurbano vs. Interior)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Conurbano</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">81,4% (n=3.525)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">78,9%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Interior</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">18,6% (n=1.501)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">21,1%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Región Educativa</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    01</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">5,2% (n=224)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">5,9%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    02</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">6,5% (n=356)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">8,5%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    03</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">8,4% (n=414)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">9,4%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    04</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">8,7% (n=328)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">9,0%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    05</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">13,7% (n=292)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">8,7%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    06</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">5,3% (n=257)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">6,0%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    07</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">6,0% (n=323)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">4,3%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    08</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">2,0% (n=211)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">6,2%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    09</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">14,6% (n=473)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">10,7%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    10</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">3,0% (n=217)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">3,6%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    11</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">7,9% (n=430)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">6,6%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    12</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,8% (n=220)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">2,0%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    13</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,4% (n=63)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,3%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    14</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,5% (n=74)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,4%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    15</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,5% (n=81)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,3%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    16</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0,2% (n=60)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">0,8%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    17</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0,5% (n=38)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">0,7%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    18</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,5% (n=103)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,7%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    19</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">3,1% (n=306)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">3,9%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    20</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0,9% (n=130)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,7%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    21</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0,2% (n=50)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">0,8%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    22</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,7% (n=201)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">2,4%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    23</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0,6% (n=51)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">0,8%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    24</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,2% (n=58)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">0,9%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    25</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">2,4% (n=66)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,3%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Ámbito</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Rural Agrupado</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">0,4% (n=152)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,4%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Rural Disperso</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">1,0% (n=175)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">1,3%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Urbano</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">98,6% (n=4.699)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">97,4%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Jornada Completa</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    NO</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">90,3% (n=4.203)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">89,1%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    SI</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">9,7% (n=823)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">10,9%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">% Alumnos con AUH</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">36,48 (0,21)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">0,36</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Media IRA Matemática</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">67,04 (0,01)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Desconocido</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">10.512</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Media IRA Lengua (PL)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">73,57 (0,03)</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Desconocido</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\">23.779</td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Media IRA Matemática (Poblacional)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">67,05</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Media IRA Lengua (Poblacional)</td>\n<td headers=\"stat_0_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0_2\" class=\"gt_row gt_center\">73,48</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"JSAobj1uICh1bndlaWdodGVkKSk7IE1lZGlhIChTRSk=\"><span class='gt_from_md'>% (n=n (unweighted)); Media (SE)</span></span></td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> <span data-qmd-base64=\"JTsgTWVkaWE=\"><span class='gt_from_md'>%; Media</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## 10. Diagnóstico Comparado de Ponderadores (3.er vs. 6.º Año)\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"brrjecbjoj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#brrjecbjoj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#brrjecbjoj thead, #brrjecbjoj tbody, #brrjecbjoj tfoot, #brrjecbjoj tr, #brrjecbjoj td, #brrjecbjoj th {\n  border-style: none;\n}\n\n#brrjecbjoj p {\n  margin: 0;\n  padding: 0;\n}\n\n#brrjecbjoj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#brrjecbjoj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#brrjecbjoj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#brrjecbjoj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#brrjecbjoj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#brrjecbjoj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#brrjecbjoj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#brrjecbjoj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#brrjecbjoj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#brrjecbjoj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#brrjecbjoj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#brrjecbjoj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#brrjecbjoj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#brrjecbjoj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#brrjecbjoj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#brrjecbjoj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#brrjecbjoj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#brrjecbjoj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#brrjecbjoj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#brrjecbjoj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#brrjecbjoj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#brrjecbjoj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#brrjecbjoj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#brrjecbjoj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#brrjecbjoj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#brrjecbjoj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#brrjecbjoj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#brrjecbjoj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#brrjecbjoj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#brrjecbjoj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#brrjecbjoj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#brrjecbjoj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#brrjecbjoj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#brrjecbjoj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#brrjecbjoj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#brrjecbjoj .gt_left {\n  text-align: left;\n}\n\n#brrjecbjoj .gt_center {\n  text-align: center;\n}\n\n#brrjecbjoj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#brrjecbjoj .gt_font_normal {\n  font-weight: normal;\n}\n\n#brrjecbjoj .gt_font_bold {\n  font-weight: bold;\n}\n\n#brrjecbjoj .gt_font_italic {\n  font-style: italic;\n}\n\n#brrjecbjoj .gt_super {\n  font-size: 65%;\n}\n\n#brrjecbjoj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#brrjecbjoj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#brrjecbjoj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#brrjecbjoj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#brrjecbjoj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#brrjecbjoj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#brrjecbjoj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#brrjecbjoj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#brrjecbjoj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"10\" class=\"gt_heading gt_title gt_font_normal\" style>Diagnóstico Comparado de Ponderadores Calibrados</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"10\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Muestras de 3.er y 6.º Año PEB 2025</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Anio\">Año</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_estudiantes\">n Muestral</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"peso_min\">Mínimo</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"peso_mediana\">Mediana</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"peso_medio\">Media</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"peso_max\">Máximo</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pesos_negativos\">Casos &lt; 0</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pesos_menores_1\">Casos &lt; 1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"suma_pesos_cal\">Suma w_cal</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"target_poblacion\">N Target Población</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Anio\" class=\"gt_row gt_left\">3.er Año</td>\n<td headers=\"n_estudiantes\" class=\"gt_row gt_right\">5230</td>\n<td headers=\"peso_min\" class=\"gt_row gt_right\">0.30</td>\n<td headers=\"peso_mediana\" class=\"gt_row gt_right\">12.43</td>\n<td headers=\"peso_medio\" class=\"gt_row gt_right\">53.43</td>\n<td headers=\"peso_max\" class=\"gt_row gt_right\">2,859.62</td>\n<td headers=\"pesos_negativos\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pesos_menores_1\" class=\"gt_row gt_right\">61</td>\n<td headers=\"suma_pesos_cal\" class=\"gt_row gt_right\">279,458</td>\n<td headers=\"target_poblacion\" class=\"gt_row gt_right\">279,458</td></tr>\n    <tr><td headers=\"Anio\" class=\"gt_row gt_left\">6.º Año</td>\n<td headers=\"n_estudiantes\" class=\"gt_row gt_right\">5026</td>\n<td headers=\"peso_min\" class=\"gt_row gt_right\">0.49</td>\n<td headers=\"peso_mediana\" class=\"gt_row gt_right\">11.88</td>\n<td headers=\"peso_medio\" class=\"gt_row gt_right\">57.85</td>\n<td headers=\"peso_max\" class=\"gt_row gt_right\">2,946.27</td>\n<td headers=\"pesos_negativos\" class=\"gt_row gt_right\">0</td>\n<td headers=\"pesos_menores_1\" class=\"gt_row gt_right\">39</td>\n<td headers=\"suma_pesos_cal\" class=\"gt_row gt_right\">290,777</td>\n<td headers=\"target_poblacion\" class=\"gt_row gt_right\">290,777</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## 11. Exportación de Bases de Estudiantes con Ponderadores\n\nEn este bloque guardo las bases finales de estudiantes (tanto en formato `.csv` como en `.rds`) conservando toda la trazabilidad de las etapas de muestreo:\n- `pi_1`: Probabilidad de inclusión del establecimiento (primera etapa - cubo).\n- `pi_2`: Probabilidad condicional de selección de la sección (segunda etapa).\n- `pi_3`: Probabilidad condicional del estudiante dentro de la sección (tercera etapa).\n- `pi_total_estudiante`: Probabilidad conjunta de inclusión ($pi_1 \\times pi_2 \\times pi_3$).\n- `weight_design`: Ponderador base / de diseño inicial ($1 / pi_{total}$).\n- `prob_respuesta` e `inv_no_respuesta`: Ajuste por propensión a la respuesta.\n- `weight_no_respuesta`: Ponderador ajustado por no respuesta ($weight\\_design \\times inv\\_no\\_respuesta$).\n- `weight_calibrate`: Ponderador final de calibración que reproduce exactamente el cuasicenso en Matemática, Lengua, Sector y NSE.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nBases exportadas con éxito en la carpeta Outputs/:\n - muestra_estudiantes_3_calibrada.csv / .rds (n = 5230 )\n - muestra_estudiantes_6_calibrada.csv / .rds (n = 5026 )\n```\n\n\n:::\n:::\n",
    "supporting": [
      "calibracion_cuasicenso_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}