---
title: "Taller Muestreo"
---

Una muestra es una parte de un todo. En los muestreos que aspiran a ser representativos (en algún grado) lo que se intenta lograr es que esa parte que se seleccione no sea muy diferente al todo. En este sentido, lo que sigue en cuanto a muestreo tiene mayor pertinencia cuando en la investigación se intenta maximizar la **representatividad** pero por alguna razón no es posible o conveniente la realización de un censo de todas las partes de ese todo.Hacer muestras también puede ser importante cuando se necesitan construir grupos de tratamiento y control en diseños experimentales.

En algunas situaciones, más usuales en las ciencias naturales, la representatividad (a veces) se logra sin un mayor esfuerzo por parte del investigador por lo que no suele ser explícitamente un objetivo de la investigación sino un supuesto más o menos implícito. Entender la razón de esto último puede ayudar a hacer más transparente alguna especificidad de las ciencias sociales en este punto. En efecto, muchos investigadores consideran que desde el nivel biológico para abajo (niveles estudiados por ejemplo por la física y la química) existe una relativa homogeneidad de los referentes. En cambio, en los niveles superiores al biológico (niveles estudiados por ejemplo por la psicología y las ciencias sociales) la variabilidad inherentes de los referentes estudiados hace que sea necesario prestar especial atención al problema de la representatividad y que el propio investigador debe realizar acciones específicas para poder captar la heterogeneidad que surge a nivel poblacional debido a la variabilidad individual de los referentes estudiados. Esta es precisamente una de las razones porque el método experimental ha sido bastante exitoso en las ciencias naturales ya que con unos pocos experimentos sus resultados se pueden inferir a su respectiva población empírica actual. No sólo eso. Muchas veces también se puede inferir a lo que a veces se denomina su universo que estaría compuesto no sólo por la población actual sino por las pasadas y las futuras.\
\
En este sentido, un físico que investiga el impacto del calor en el átomo de carbono puede tener una razonable confianza que el átomo de carbono no sólo es muy similar a los otros átomos de carbono actuales sino también a los pasados y los futuros átomos de carbono. También puede tener confianza que los átomos de carbono encontrados en la tierra son similares a los existentes en el resto del universo. En cambio, un científico social que investiga la relación entre sociedades capitalistas y desigualdad se encuentra bastante lejos de esa confianza. En efecto, el científico social intuye que dentro de ese concepto entran muchas sociedades que, a pesar de todas cumplir los requisitos para ser clasificada como capitalista, pueden variar de modo crítico, no sólo en su desigualdad (que es un punto que explícitamente él quiere investigar) sino en una serie de otros factores. En este sentido, si un investigador que observó a las sociedades capitalistas actuales infiere sus resultados al **universo** de las sociedades capitalistas, esto es, a la clase de referencia formado por el conjunto de las sociedades capitalistas que existieron, existen y existirán, puede tener un fuerte problema de **representatividad** porque difícilmente haya captado toda la **heterogeneidad** de las clase formada por el conjunto de sociedades capitalistas.\
\
Dada la introducción anterior, ahora estamos en condiciones de expresarlo lo mismo pero en términos más simples. Donde no hay heterogeneidad con seguridad no hay problemas de representatividad. Si hay heterogeneidad y el investigador no realiza acciones en su diseño para incluir esa heterogeneidad en su investigación la misma tendrá un problema de **validez externa**. Las muestras que aspiran a ser representativas intentan captar la heterogeneidad de una determinada población.\

## Muestras de qué?

\
Por lo tanto un primer paso importante cuando uno se preocupa por la representatividad es entender sobre que población de referentes y de unidades de observación/experimentación uno va a querer predicar sus inferencias. Para eso hay que analizar: \
\
a) La clase de referencia de los conceptos utilizados que nos dirá el tipo de referente a investigar (individuos, organizaciones, etc.). Esto a veces se suele denominar **universo** de la teoría o universo del discurso.

\
b) Los objetivos de la investigación que nos indicaran el alcance (usualmente especificando tiempo y espacio) y otras características pertinentes de cada unidad de observación/experimentación.\
\
Las **propiedades generales**, como su nombre lo indica, sirven para construir **géneros** y todas los objetos reales que pertenecen a ese género tienen el mismo valor en todas sus propiedades generales. Ejemplo: Todo objeto real que se clasifique como "persona" deberá cumplir una serie de propiedades generales que hacen a la esencia de "persona" y se incluyen en su definición. Ser argentino o vivir en Buenos Aires no pertenece a un valor de una propiedad general de las personas. En cambio, mamífero descendiente del mono sí. Las propiedades generales nos ayudan a identificar la clase de referencia pero todavía falta una mayor especificación para construir la población sobre la cual se realizará la muestra. 

Las **propiedades específicas** sirven para construir **especies de los géneros** en función de los diferentes valores en las propiedades específicas. Tiempo y espacio son típicas propiedades específicas que ayudan recortar al universo anterior delimitando una población. Luego pueden existir otras propiedades específicas (como las anteriores de ser argentino o vivir en Buenos Aires) que sirven para seguir delimitando aún más nuestra población. \
\
En el muestreo aplicado, al conjunto formado por todos los objetos reales que cumplan las propiedades generales y específicas explicitada se lo denomina **población**. 

En nuestra vida cotidiana, aunque sea sólo por vivir en un tiempo y espacio determinado (y aún si somos investigadores científicos profesionales) usualmente sólo tenemos posibilidad de acceso empírico a un subconjunto de aquella población. Para empeorar las cosas, en las ciencias sociales muchas poblaciones son muy numerosas, heterogéneas y/o otras se encuentran muy separadas espacialmente lo que dificulta y hace costoso llegar a cada uno de las partes de aquellas. En algunos casos, el investigador tiene el problema adicional de trabajar con poblaciones "invisibles" de las que se sabe que existen pero no se tienen datos agregados de ella y es sumamente difícil identificar/contactar a miembros de ella. Ante esta situación el investigador tiene 2 grandes opciones:

a\) Se ajustan los objetivos de las investigación, especialmente en lo tocante al grado de alcance o generalidad de la investigación, hasta un punto que efectivamente la definición de la unidad de análisis construya una población abordable y/o

b\) Se realiza una **muestra** de aquella población.

En este sentido, en lo que sigue se le prestará atención a las estrategias tipo ‘b’ como un modo de con ‘poco’ inferir ‘bastante’, aun cuando, en muchos casos, no se sepa a ciencia cierta si ese ‘bastante’ es ‘suficiente’. En otras palabras, se verán las distintas características de los diferentes tipos de muestras que aspiran a algún grado de representatividad y comprender cual de ellos puede ser más idóneo para los objetivos de las diferentes investigaciones. \
\
Existen varios criterios para clasificar a las muestras. Algunos de ellos, como todos los que se basan en algún modo en la aleatoriedad y la heterogeneidad esperada, ponen el acento en el **proceso** de la muestra. Otros, como todos los que se basan en el criterio de saturación y en la heterogeneidad observada, ponen más acento en el **resultado o producto final**. Finalmente, en el último tiempo se han perfeccionado una serie de técnicas que permiten mejorar muestras ya realizadas siempre y cuando tanto en la muestras como en la población se tengan datos similares y donde el segundo se considera como un **gold standard** del primero.
