---
title: "muestras_complejas"
---

## Muestras complejas

Las muestras complejas son una familia de muestras que tienen en común la combinación de diseños muestrales más simples como los vistos anteriormente. En general, esta combinación se produce en pasos o etapas por lo que también se los suele denominar "muestreos polietápicos". Desde un punto de vista más práctico esta combinación se suele realizar para aprovechar la posible sinergia entre los pro y contras de cada tipo de muestreo sea tanto para producir muestras más baratas (lo que suele redundar en más viabilidad) o más precisas. Desde un punto de vista más teórico las muestras complejas tienen el problema que es más difícil luego trabajar con ellas dado que es más difícil calcular los ponderadores y los márgenes de error ya que se combinan los respectivos de cada etapa.

Esto último no es un problema menor. En efecto, en la historia de las técnicas de muestreo los muestristas de la segunda mitad del siglo XX ya sabían que "mezclar" diferentes tipos de muestreo clásicos en diferentes etapas tenía benefi s "efectos de diseño" (*design effect o deff*) que facilitó durante décadas los análisis de los datos de este tipo de muestras.

La estrategia que se encuentra por detrás del concepto de efecto de diseño es relativamente simple de interpretar y de ahí su popularidad [@kish1965]. Es un coeficiente que dice que tanto más chico o que tanto más grande es el error del diseño de una muestra compleja - comparada contra el error de una muestra con un diseño de azar simple. Esta simplicidad en su interpretación permitió dos fenómenos complementarios. Por un lado permitió que cobre visibilidad algunos de los beneficios de las estrategias de los muestristas que insistían en la combinación de tipos de muestreos. Por otro lado, permitió que los analistas de datos dejen de analizar esas muestras como si fueran muestras con diseños simples y pasen a un estadio más realista en donde al cálculo anterior se lo ajusta por el factor "efecto de diseño". El ideal sería que ese factor de diseño se calcule para cada variable específica que se analiza (esto también aplica para las muestras con diseños simples) pero esto, gracias al aumento de las potencias de las computadoras y el crecimiento de programas y librerías especializadas, sólo es factible en tiempos contemporáneos. Antes, este coeficiente lo calculaba una vez del muestrista y luego se lo pasaba a quienes iban a realizar el análisis de datos y estos, en general, luego lo aplicaban/extendían a todas las variables que analizaban.

El ejemplo más típico de muestra compleja quizá sea el que primero conglomera y luego aplica, en un segundo o tercer paso, otros diseños como el estratificado o el sistemático. Otro ejemplo de muestra compleja puede considerarse el caso de una muestra que primero realiza un PPS y luego realiza un muestreo sistemático o simple de una cantidad fija en cada caso seleccionado en la primera etapa.

The overall sampling probability of an element is the product of the sampling probabilities at each stage: if a cluster is sampled with probability 1/100 and a household is sampled from that cluster with probability 1/1000, the sampling probability for the householdis ni = 1/1OOx 1/1000,andthe sampling weight is lOOx 1000 = 100000. Some technical conditions on the sampling design are needed for probabilities to work out in this simple way. The two most important are that every individual must be in one and only one cluster, and that the subsampling probabilities for any given cluster do not depend on which other clusters were sampled ([@lumley2010, pag. 41].
