# Cuando y porqué hacer muestras

Una muestra es una parte de un todo. En los muestreos que aspiran a ser (en algún grado) representativos lo que se intenta lograr es que esa parte que se seleccione no sea muy diferente al todo o, como decían los romanos, que sea legítimo tomar una parte como el todo (*pars pro toto*). En este sentido, lo que vamos a hablar aquí sobre muestreo tiene mayor pertinencia cuando en la investigación se intenta maximizar la **representatividad** pero por alguna razón no es posible o conveniente la realización de un censo de todas las partes que conforman ese todo. Por otro lado, diseñar muestras también puede ser importante cuando se necesitan construir grupos de tratamiento y control en diseños experimentales, especialmente en los diseños experimentales aleatorios [@kish1987]. En efecto, la vinculación entre la bibliografía del diseño muestral y del diseños experimental suele ser útil si se aspira a entender las razones (y no sólo saber ejecutarlas en la práctica) de algunas recomendaciones metodológicas ya que muchos de los conceptos más abstractos son compartidos por ambas [@hedlin2015][@fienberg1988].

::: callout-note
Las muestras que aspiran a ser representativas intentan captar la heterogeneidad de una determinada población para poder hablar legítimamente del todo a través de sólo una parte.
:::

En algunas situaciones, más usuales en las ciencias naturales, la representatividad a veces se logra sin un mayor esfuerzo por parte del investigador por lo que no suele ser explícitamente un objetivo de la investigación sino un supuesto más o menos implícito a lo largo de ella. En otras palabras, la hipótesis de la homogeneidad forma parte del modelo mediante el cual se intenta aprendeder de la realidad. Entender la razón de esto último puede ayudar a hacer más transparente alguna especificidad de las ciencias sociales en este punto. En efecto, muchos investigadores consideran que en los niveles más bajos de la realidad (p.e. niveles estudiados por la física y la química) existe una mayor homogeneidad de los referentes básicos que estudian esas disciplinas. En cambio, en los niveles más superiores (p.e. niveles estudiados por ejemplo por la psicología y las ciencias sociales) la variabilidad inherentes de los referentes estudiados hace que sea necesario prestar especial atención al problema de la representatividad, En este sentido, el investigador suele realizar acciones específicas para poder captar la heterogeneidad que surge a nivel poblacional debido a la variabilidad individual de los referentes estudiados y, en ese camino, suele venir en ayuda el diseño muestral.

De manera derivada, lo anterior es una de las razones porque el método experimental ha sido bastante exitoso en la historia de las ciencias naturales ya que con unos pocos experimentos sus resultados se pueden inferir a su respectiva **población** empírica actual. No sólo eso. Muchas veces también se puede inferir a lo que a veces se denomina su **universo** que estaría compuesto no sólo por la población actual sino también por la clase de esas poblaciones pasadas y futuras. Este tipo de problemáticas son conocidas por diferentes disciplinas. Desde la epistemología a veces de los relaciona con el problema de los universales [@klima2022] y desde la metodología se lo relaciona con el problema de la **validez externa** de las investigaciones [@campbell1963].\
\
A modo de ejemplo, un físico que investiga el impacto del calor en el átomo de carbono puede tener una razonable confianza que el átomo de carbono que está hoy estudiando no sólo es muy similar a los otros átomos de carbono actuales en la Tierra (población) sino que también es similar a los pasados y los futuros átomos de carbono (universo). También puede tener confianza que los átomos de carbono encontrados en la Tierra son similares a los existentes en el resto del universo. En el otro extremo, este tipo se suposiciones en general son difíciles de mantener en el nivel social.

Estas diferencias en cuanto a la validez externa no son tan marcadas cuanto se analiza la dimensión de la **validez interna** de las investigaciones. En la jerga de la bibliografía de los diseños de investigación se suele afirmar que en todas las investigaciones que se quiera realizar inferencias causales, independientemente si se trata de investigaciones físicas o sociales, el investigador se debe asegurar, en la fase de diseño de la investigación, de controlar o aleatorizar el conjunto de factores extraños que le sugiera/n la o las teorías utilizadas. Esto es lo que precisamente le asegurará que aquellos factores extraños no sigan existiendo como factores perturbadores que puedan invalidar las inferencias internas o locales en el momento de las conclusiones [@kish1987]. En el último tiempo la visión anterior se ha expandido aún más permitiendo mayor seguridad en diseños observacionales en situaciones en donde no es posible un diseño experimental aleatorio lo que es sumamente importante en el dominio de las ciencias sociales [@pearl2018a; @morgan2015].

Dada la introducción anterior, ahora estamos en condiciones de expresar lo mismo pero en términos más simples:

::: callout-note
Donde no hay heterogeneidad con seguridad no hay problemas de representatividad. Si hay heterogeneidad, y el investigador no realiza acciones en su diseño para incluir esa heterogeneidad en su investigación, la misma sufrirá de un problema de representatividad que derivará en un problema de **validez externa**.
:::

## Muestras de qué?

\
Un primer paso importante cuando uno se preocupa por la representatividad es entender sobre que población de referentes y de unidades de observación/experimentación uno va a querer predicar sus inferencias. Para eso hay que analizar: \
\
a) La clase de referencia de los conceptos utilizados que nos dirá el/los tipo/s de referente/s a investigar (individuos, organizaciones, etc.). Esto a veces se suele denominar **universo** o dominio de la teoría [@bunge1974a].

b\) Los objetivos de la investigación que nos indicaran, entre otras cuestiones, el alcance (usualmente especificando tiempo y espacio) de los referentes anteriores junto con otras características pertinentes de cada unidad de observación/experimentación. Usualmente los objetivos remiten a una población empírica que podrá grande o pequeña, homogénea o heterogénea, dispersa o aglomerada, etc. \
\
Dentro del muestreo al conjunto formado por todos los objetos reales que cumplan las condiciones de los puntos "a" y "b" se lo denomina **población**[^muestras-1]. En nuestra vida cotidiana, aunque sea sólo por vivir en un tiempo y espacio determinado (y aún si somos investigadores de profesión) usualmente sólo tenemos posibilidad de acceso empírico a un subconjunto de aquella población. Para empeorar las cosas, en las ciencias sociales muchas poblaciones son muy numerosas, heterogéneas y/o otras se encuentran muy separadas espacialmente lo que dificulta y hace costoso llegar a cada uno de las partes de aquellas. En el extremo, a veces el investigador tiene el problema adicional de trabajar con poblaciones "invisibles" de las que se sabe o se presupone que existen pero no se tienen datos agregados de ella y/o es sumamente difícil identificar/contactar a miembros de ella. Ante esta situación el investigador tiene 2 grandes opciones:

a\) Se ajustan los objetivos de las investigación, especialmente en lo tocante al grado de alcance o generalidad de la investigación, hasta un punto que efectivamente la definición de la unidad de análisis construya una población en la que se pueda abordable empíricamente a cada una de las unidades que la componen y/o

b\) Se realiza una **muestra** de aquella población.

En este sentido, en este taller se le prestará atención a las estrategias tipo ‘b’ como un modo de conocer el todo a través de sólo una parte de aquel. Más adelante también veremos que hay estrategias más eficientes que otras para con ‘poco’ inferir ‘bastante’, aun cuando, en muchos casos, no se sepa a ciencia cierta si ese ‘bastante’ es ‘suficiente’. En otras palabras, se verán las distintas características de diferentes diseños muestrales que aspiran a algún grado de representatividad y comprender cual de ellos puede ser más idóneo en función de los objetivos, el presupuesto y los datos disponibles en cada caso. \
\
Existen varios criterios para clasificar a las muestras. Siguiendo una clasificación clásica [@neyman1934], todos los que se basan en algún modo en la aleatoriedad (*random*), ponen el acento en el **proceso** de la muestra y se las puede clasificar como **muestras probabilísticas**. Otros, como todos los que se basan en cuotas ponen más acento en las acciones y chequeos basados en las intenciones (*purposive*) del **resultado o producto final.** Aquí,más que usar el término de muestras intencionales de Neyman vamos a preferir el más amplio de muestras no probabilísticas ya que también engloba a otros diseños que tienen la similitud, al menos a primera vista, de no ser probabilísticos [@baker2013]. Ejemplos pueden considerarse las muestras basadas en el criterio de saturación y la heterogeneidad observada, los muestreos por conveniencia, los muestreos por matcheo (en donde los cuotas de Neyman serían un ejemplo), los muestreos basados en redes, usuales para el estudio de poblaciones invisibles (en donde el bola de nieve sería un ejemplo).

Finalmente en el último tiempo, y en parte por el avance de una mayor disponibilidad de información secundaria, cada vez existen más métodos que permiten incorporar esa mayor información secundaria como información auxiliar (*auxiliary information*) tanto en el diseño de la muestra como en el posterior ajuste de los estimadores de la misma. Este último proceso en particular se suele denominar calibración. Ambos usos de la información secundaria (tanto si se usan para el diseño *ex-ante* o para el ajuste de los estimadores *ex-post*) son ejemplos de diseños muestrales asistidos por modelos que derivan de información secundaria (*model assisted*).

En el útimo párrafo, casi al pasar, se ha comentado que "en el último tiempo" ha habido cambios en el mundo del muestreo. Más allá que se pueda afirmar que en algunos momentos haya habido más cambios que otros, la historia de la incorporación de las diferentes teorías de muestreo en la estadística como disciplina (antes dominada por aplicaciones sobre poblaciones enteras o censos) o en el diseño de investigaciones (antes dominada por diseños experimentales) es sumamente interesante y recomendable [@hacking2004; @hacking2006; @gigerenzer1997].

```         
::: {.sectionrefs} :::
```

[^muestras-1]: Expresado en términos de propiedades generales y específicas podría afirmarse que las **propiedades generales**, como su nombre lo indica, sirven para construir **géneros** y todas los objetos reales que pertenecen a ese género tienen el mismo valor en todas sus propiedades generales. Ejemplo: Todo objeto real que se clasifique como "persona" deberá cumplir una serie de propiedades generales que hacen a la esencia de "persona" y se incluyen en su definición. Ser estudiante o residir en la provincia de Buenos Aires no pertenece a un valor de una propiedad general de las personas. En cambio, mamífero descendiente del mono, sí. Las propiedades generales son necesarios para identificar la clase de referencia pero no suficientes para construir la población sobre la cual se realizará la muestra. 

    Las **propiedades específicas,** también como su nombre lo sugiere**,** sirven para construir **especies de los géneros** en función de los diferentes valores en las propiedades específicas. Tiempo y espacio son típicas propiedades específicas que ayudan recortar al universo anterior delimitando una población empírica. Luego pueden existir otras propiedades específicas (como las anteriores de ser estudiante o vivir en Buenos Aires) que sirven para seguir delimitando aún más nuestra población.
