---
title: "Taller Muestreo"
format: html
editor: visual
code-fold: true
code-tools:
      source: true
      toggle: true
      caption: "Código"
---

## 

Una muestra es una parte de un todo. En los muestreos que aspiran a ser representativos (en algún grado) lo que se intenta lograr es que esa parte que se seleccione no sea muy diferente al todo. En este sentido, lo que sigue en cuanto a muestreo tiene mayor pertinencia cuando en la investigación se intenta maximizar la **representatividad** pero por alguna razón no es posible la realización de un censo de todas las partes de ese todo.También puede ser importante cuando se intentan De modo complementario se puede afirmar que mucha de la discusión que sigue no es (tan) pertinente es investigaciones en donde se intente maximizar el realismo, la aleatorización o alguna combinación de ellas. En algunas situaciones, más usuales en las ciencias naturales, la representatividad (a veces) se logra sin un mayor esfuerzo por parte del investigador por lo que no suele ser explícitamente un objetivo de la investigación sino un supuesto más o menos implícito. Entender la razón de esto último puede ayudar a hacer más transparente alguna especificidad de las ciencias sociales en este punto. En efecto, muchos investigadores consideran que desde el nivel biológico para abajo (niveles estudiados por la física y la química) existe una relativa homogeneidad de los referentes. En cambio, en los niveles superiores al biológico (niveles estudiados por la psicología y las ciencias sociales) la variabilidad inherentes de los referentes estudiados hace que sea necesario prestar especial atención al problema de la representatividad y que el propio investigador debe acciones específicas para poder captar la heterogeneidad que surge a nivel poblacional de la variabilidad individual de los referentes estudiados.\
\
Siguiendo el vocabulario introducido en la introducción de la unidad 2 se podría afirmar que no sólo existen cosas sino que también existen diferentes tipos de cosas. Por ejemplo, un átomo no es es mismo tipo de cosa que una molécula, una célula, un organismo, una persona o una sociedad. Todos son cosas pero se podría afirmar que son diferentes tipos de cosas. Independientemente de como se defina cada uno de los términos anteriores es claro que, a medida que se va aumentando el nivel de integración (átomo \> molécula \> célula \> organismo \> sociedad), el modo en que se combinan los átomos para construir cosas más complejas puede variar cada vez más admitiendo una **mayor heterogeneidad** dentro de un mismo tipo de cosa.\
\
Un físico que investiga el impacto del calor en el átomo de carbono puede tener una razonable confianza que el átomo de carbono no sólo es muy similar a los otros átomos de carbono actuales sino también a los pasados y los futuros átomos de carbono. También puede tener confianza que los átomos de carbono encontrados en la tierra son similares en todo el universo. En cambio, un científico social que investiga la relación entre sociedades capitalistas y desigualdad se encuentra bastante lejos de esa confianza. En efecto, el científico social intuye que dentro de ese concepto entran muchas sociedades que, a pesar de todas cumplir los requisitos para ser clasificada como capitalista, pueden variar de modo crítico, no sólo en su desigualdad (que es un punto que explícitamente él quiere investigar) sino en una serie de otros factores. En este sentido, si un investigador que observó una sola sociedad capitalista infiere sus resultados al **universo** de las sociedades capitalistas, esto es, a la clase de referencia formado por el conjunto de las sociedades capitalistas que existieron, existen y existirán, puede tener un fuerte problema de **representatividad** porque difícilmente haya captado toda la **heterogeneidad** de las sociedades capitalistas. \
\
Dada la introducción anterior, ahora estamos en condiciones de expresarlo en término más simples. Si hay heterogeneidad puede haber problemas de representatividad independientemente si el investigador toma explícitamente a la representatividad como un objetivo a maximizar en su diseño de investigación. Por otro lado, donde no hay heterogeneidad con seguridad no hay problemas de representatividad. Por eso, entre otras razones, muchas investigaciones de las ciencias naturales, realizadas en laboratorios y con (relativos) pocos casos, suelen funcionar sin problemas de representatividad.\
\
Aclarado el problema general de la representatividad ahora podemos pasar al problema de las unidades de observación. Acá también primero lo vamos a relacionar con otro texto que vimos sobre el tema del diseño de investigación. Babbie afirmaba que en ciencias sociales podían existir varios tipos de unidades de análisis (acá "referentes" en el nivel gnoseológicos y "unidades de observación/experimentación" en el nivel metodológico). Distinguía entre individuos, grupos, organizaciones y productos sociales. De modo bastante independiente a como se define a cada uno de ellos es claro que, una vez definidos, se tratan de tipos de cosas diferentes y distinguibles entre sí. \
\
Por lo tanto un primer paso importante cuando uno se preocupa por la representatividad es entender sobre que población de referentes y de unidades de observación/experimentación uno va a querer predicar sus inferencias. Para eso hay que analizar: \
\
a) La clase de referencia de los conceptos utilizados que nos dirá el tipo de referente a investigar (individuos, organizaciones, etc.). Esto a veces se suele denominar **universo** de la teoría o universo del discurso.\
b) Los objetivos de la investigación que nos indicaran el alcance (usualmente especificando tiempo y espacio) y otras características pertinentes de cada unidad de observación/experimentación.\
\
Las **propiedades generales**, como su nombre lo indica, sirven para construir **géneros** y todas los objetos reales que pertenecen a ese género tienen el mismo valor en todas sus propiedades generales. Ejemplo: Todo objeto real que se clasifique como "persona" deberá cumplir una serie de propiedades generales que hacen a la esencia de "persona". Ser argentino o vivir en Buenos Aires no pertenece a un valor de una propiedad general de las personas. En cambio, mamífero descendiente del mono sí. Las propiedades generales nos ayudan a identificar la clase de referencia o el tipo de unidad de análisis (en el sentido de Babbie) pero todavía falta una mayor especificación para construir nuestra población de unidades de análisis. 

Las **propiedades específicas** sirven para construir **especies de esos géneros** en función de los diferentes valores en las diferentes propiedades específicas. Tiempo y espacio son típicas propiedades específicas que especifican al universo anterior delimitando una población. Luego pueden existir otras propiedades específicas (como las anteriores de ser argentino o vivir en Buenos Aires) que sirven para seguir delimitando aún más nuestra población. \
\
Al conjunto formado por todos los objetos reales que cumplan las propiedades generales y específicas explicitada se lo denomina **población**. 

En nuestra vida cotidiana, aunque sea sólo por vivir en un tiempo y espacio determinado (y aún si somos investigadores científicos profesionales) usualmente sólo tenemos posibilidad de acceso empírico a un subconjunto de aquella población. Para empeorar las cosas, en las ciencias sociales muchas poblaciones son muy numerosas, heterogéneas y/o otras se encuentran muy separadas espacialmente lo que dificulta y hace onerosa llegar a cada uno de las partes de aquellas. En algunos casos, el investigador tiene que enfrentarse al problema de trabajar con poblaciones "invisibles" de las que se sabe que existen pero no se tienen datos agregados de ella y es sumamente difícil identificar/contactar a miembros de ella.  Ante esta situación el investigador tiene 2 grandes opciones:

a\) Se ajustan los objetivos de las investigación, especialmente en lo tocante al grado de alcance o generalidad de la investigación, hasta un punto que efectivamente la definición de la unidad de análisis construya una población abordable y/o

b\) Se realiza una **muestra** de aquella población.

En este sentido, en esta unidad se le dedicará bastante atención a las estrategias tipo ‘b’ como un modo de con ‘poco’ inferir ‘bastante’, aun cuando, en muchos casos, no se sepa a ciencia cierta si ese ‘bastante’ es ‘suficiente’. En otras palabras, se verán las distintas características de los diferentes tipos de muestras que aspiran a algún grado de representatividad y comprender cual de ellos puede ser más idóneo para los objetivos de las diferentes investigaciones. \
\
Existen varios criterios para clasificar a las muestras. Algunos de ellos, como todos los que se basan en algún modo en la aleatoriedad y la heterogeneidad esperada, ponen el acento en el **proceso** de la muestra. Otros, como todos los que se basan en el criterio de saturación y en la heterogeneidad observada, ponen más acento en el **resultado o producto final**. En cualquier caso ambas estrategias recomiendan planificar el proceso real de selección en el contexto que se aplica. En efecto, la temática del muestreo es una técnica que posee dimensiones tanto cercanas a una tecnología como también cercanos a una técnica empíricas. La razón es que si bien existen reglas más o menos claras, algunas de ellas son tan difíciles de cumplir en la realidad que el modo, muchas veces imaginativo, en que ellas se aplican es determinante.
